replicaCount: 1

image:
  repository: nginxmatdurand/cicd-demo-app
  tag: 1.1.1-master-latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}
