apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
{{ include "helm-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: {{ include "helm-chart.name" . }}-secrets-volume
          mountPath: "/var/secrets"
          readOnly: true
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "helm-chart.name" . }}-configmap
        env:
        - name: SECRET_CARAMILK
          valueFrom:
            secretKeyRef:
              name: {{ include "helm-chart.name" . }}-secrets
              key: caramilk_secret
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ include "helm-chart.name" . }}-secrets-volume
        secret:
          secretName: {{ include "helm-chart.name" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
