apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm-chart.labels" . | indent 4 }}
  name: {{ include "helm-chart.name" . }}-secrets
type: Opaque
data:
  caramilk_secret: {{ default "" .Values.secrets.caramilkSecret | b64enc | quote }}
