apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "helm-chart.name" . }}
  name: {{ include "helm-chart.name" . }}-secrets
type: Opaque
data:
  caramilk_secret: {{ default "" .Values.secrets.caramilkSecret | b64enc | quote }}
