name: CI
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 10.15.0
            - name: Installing dependencies
              run: npm ci
            - name: Running tests
              run: npm test
            - name: Build Docker image
              run: |
                export PACKAGE_CURRENT_VERSION="$(npx -c 'echo "$npm_package_version"')"
                export COMMIT_HASH=${GITHUB_SHA:0:8}
                export GIT_BRANCH=$(echo "$GITHUB_REF" | tr '[:upper:]' '[:lower:]' | sed 's/refs\/heads\///g' | sed 's/[\/]/-/g' | sed 's/[^a-z0-9._-]//g')
                export DOCKER_TAG_BASE=docker.pkg.github.com/matdurand/cicd-demo-app/${PACKAGE_CURRENT_VERSION}-${GIT_BRANCH}
                export DOCKER_TAG_COMMIT=${DOCKER_TAG_BASE}:${COMMIT_HASH}
                export DOCKER_TAG_LATEST=${DOCKER_TAG_BASE}:latest
                docker build . -t ${DOCKER_TAG_COMMIT} -t ${DOCKER_TAG_LATEST}
                echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
                docker push ${DOCKER_TAG_COMMIT}
                docker push ${DOCKER_TAG_LATEST}
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}